# slug: (display name, region group, filter type, QID(s), tmdb lang, extra country filter)
# type 'lang' = original language (P364); 'country' = country of origin (P495)
I = {
 # India (by language)
 "bollywood":("Bollywood","India","lang","Q1568","hi","Q668"),
 "tollywood":("Tollywood","India","lang","Q8097","te",None),
 "kollywood":("Kollywood","India","lang","Q5885","ta","Q668"),
 "mollywood":("Mollywood","India","lang","Q36236","ml",None),
 "sandalwood":("Sandalwood","India","lang","Q33673","kn",None),
 "bengali-tollywood":("Tollywood (Bengali)","India","lang","Q9610","bn","Q668"),
 "marathi":("Marathi cinema","India","lang","Q1571","mr",None),
 "pollywood":("Pollywood","India","lang","Q58635","pa","Q668"),
 "dhollywood":("Dhollywood","India","lang","Q5137","gu",None),
 "ollywood":("Ollywood","India","lang","Q33810","or",None),
 "jollywood":("Jollywood","India","lang","Q29401","as",None),
 "bhojiwood":("Bhojiwood","India","lang","Q33268","bh",None),
 "chhollywood":("Chhollywood","India","lang","Q33158","hne",None),
 "coastalwood":("Coastalwood (Tulu)","India","lang","Q34251","tcy",None),
 "konkani":("Konkani cinema","India","lang","Q34239","kok",None),
 "manipuri":("Manipuri cinema","India","lang","Q33868","mni",None),
 "rajasthani":("Rajasthani cinema","India","lang","Q13196","raj",None),
 "haryanvi":("Haryanvi cinema","India","lang","Q33410","bgc",None),
 # Rest of South Asia (by country)
 "lollywood":("Lollywood","South Asia","country","Q843",None,None),
 "dhallywood":("Dhallywood","South Asia","country","Q902",None,None),
 "nepal":("Kollywood (Nepal)","South Asia","country","Q837",None,None),
 "srilanka":("Sri Lankan cinema","South Asia","country","Q854",None,None),
 # East & SE Asia
 "china":("Chinese cinema","East & Southeast Asia","country","Q148",None,None),
 "hongkong":("Hong Kong cinema","East & Southeast Asia","country","Q8646",None,None),
 "taiwan":("Taiwanese cinema","East & Southeast Asia","country","Q865",None,None),
 "korea":("Korean cinema","East & Southeast Asia","country","Q884",None,None),
 "japan":("Japanese cinema","East & Southeast Asia","country","Q17",None,None),
 "thailand":("Thai cinema","East & Southeast Asia","country","Q869",None,None),
 "philippines":("Philippine cinema","East & Southeast Asia","country","Q928",None,None),
 "indonesia":("Indonesian cinema","East & Southeast Asia","country","Q252",None,None),
 "vietnam":("Vietnamese cinema","East & Southeast Asia","country","Q881",None,None),
 "malaysia":("Malaysian cinema","East & Southeast Asia","country","Q833",None,None),
 # Americas
 "hollywood":("Hollywood","Americas","country","Q30",None,None),
 "canada":("Canadian cinema","Americas","country","Q16",None,None),
 "mexico":("Mexican cinema","Americas","country","Q96",None,None),
 "brazil":("Brazilian cinema","Americas","country","Q155",None,None),
 "argentina":("Argentine cinema","Americas","country","Q414",None,None),
 "colombia":("Colombian cinema","Americas","country","Q739",None,None),
 "chile":("Chilean cinema","Americas","country","Q298",None,None),
 "cuba":("Cuban cinema","Americas","country","Q241",None,None),
 # Europe
 "uk":("British cinema","Europe","country","Q145",None,None),
 "france":("French cinema","Europe","country","Q142",None,None),
 "italy":("Italian cinema","Europe","country","Q38",None,None),
 "germany":("German cinema","Europe","country","Q183",None,None),
 "spain":("Spanish cinema","Europe","country","Q29",None,None),
 "russia":("Russian cinema","Europe","country","Q159",None,None),
 "denmark":("Danish cinema","Europe","country","Q35",None,None),
 "sweden":("Swedish cinema","Europe","country","Q34",None,None),
 "norway":("Norwegian cinema","Europe","country","Q20",None,None),
 "finland":("Finnish cinema","Europe","country","Q33",None,None),
 "iceland":("Icelandic cinema","Europe","country","Q189",None,None),
 "poland":("Polish cinema","Europe","country","Q36",None,None),
 "czechia":("Czech cinema","Europe","country","Q213",None,None),
 "ireland":("Irish cinema","Europe","country","Q27",None,None),
 "greece":("Greek cinema","Europe","country","Q41",None,None),
 "romania":("Romanian cinema","Europe","country","Q218",None,None),
 # Middle East & Africa
 "nollywood":("Nollywood","Middle East & Africa","country","Q1033",None,None),
 "ghallywood":("Ghallywood","Middle East & Africa","country","Q117",None,None),
 "riverwood":("Riverwood","Middle East & Africa","country","Q114",None,None),
 "bongowood":("Bongowood","Middle East & Africa","country","Q924",None,None),
 "southafrica":("South African cinema","Middle East & Africa","country","Q258",None,None),
 "egypt":("Egyptian cinema","Middle East & Africa","country","Q79",None,None),
 "turkey":("Turkish cinema","Middle East & Africa","country","Q43",None,None),
 "iran":("Iranian cinema","Middle East & Africa","country","Q794",None,None),
 "israel":("Israeli cinema","Middle East & Africa","country","Q801",None,None),
 "morocco":("Moroccan cinema","Middle East & Africa","country","Q1028",None,None),
 # Oceania
 "australia":("Australian cinema","Oceania","country","Q408",None,None),
 "newzealand":("New Zealand cinema","Oceania","country","Q664",None,None),
}
