-- 68 film industries
insert or ignore into industries (slug,name,language_code,region,description,sort_order) values
('bollywood','Bollywood','hi','India','Hindi cinema (Mumbai)',0),
('tollywood','Tollywood','te','India','Telugu cinema (Hyderabad)',1),
('kollywood','Kollywood','ta','India','Tamil cinema (Chennai)',2),
('mollywood','Mollywood','ml','India','Malayalam cinema (Kochi)',3),
('sandalwood','Sandalwood','kn','India','Kannada cinema (Bengaluru)',4),
('bengali-tollywood','Tollywood (Bengali)','bn','India','Bengali cinema (Kolkata)',5),
('marathi','Marathi cinema','mr','India','Marathi cinema (Mumbai, Pune)',6),
('pollywood','Pollywood','pa','India','Punjabi cinema',7),
('dhollywood','Dhollywood','gu','India','Gujarati cinema',8),
('ollywood','Ollywood','or','India','Odia cinema',9),
('jollywood','Jollywood','as','India','Assamese cinema',10),
('bhojiwood','Bhojiwood','bh','India','Bhojpuri cinema',11),
('chhollywood','Chhollywood','hne','India','Chhattisgarhi cinema',12),
('coastalwood','Coastalwood','tcy','India','Tulu cinema',13),
('konkani','Konkani cinema','kok','India','Konkani cinema (Goa)',14),
('manipuri','Manipuri cinema','mni','India','Meitei cinema (Manipur)',15),
('rajasthani','Rajasthani cinema','raj','India','Rajasthani cinema',16),
('haryanvi','Haryanvi cinema','bgc','India','Haryanvi cinema',17),
('lollywood','Lollywood',null,'South Asia','Pakistan (Lahore, Karachi)',18),
('dhallywood','Dhallywood',null,'South Asia','Bangladesh (Dhaka)',19),
('nepal','Kollywood (Nepal)',null,'South Asia','Nepal (Kathmandu)',20),
('srilanka','Sri Lankan cinema',null,'South Asia','Sri Lanka (Sinhala and Tamil)',21),
('china','Chinese cinema',null,'East & Southeast Asia','Mainland China',22),
('hongkong','Hong Kong cinema',null,'East & Southeast Asia','Hong Kong',23),
('taiwan','Taiwanese cinema',null,'East & Southeast Asia','Taiwan',24),
('korea','Korean cinema',null,'East & Southeast Asia','South Korea (Chungmuro)',25),
('japan','Japanese cinema',null,'East & Southeast Asia','Japan',26),
('thailand','Thai cinema',null,'East & Southeast Asia','Thailand',27),
('philippines','Philippine cinema',null,'East & Southeast Asia','Philippines',28),
('indonesia','Indonesian cinema',null,'East & Southeast Asia','Indonesia',29),
('vietnam','Vietnamese cinema',null,'East & Southeast Asia','Vietnam',30),
('malaysia','Malaysian cinema',null,'East & Southeast Asia','Malaysia',31),
('hollywood','Hollywood',null,'Americas','United States (Los Angeles)',32),
('canada','Canadian cinema',null,'Americas','Canada (English and Québécois)',33),
('mexico','Mexican cinema',null,'Americas','Mexico',34),
('brazil','Brazilian cinema',null,'Americas','Brazil',35),
('argentina','Argentine cinema',null,'Americas','Argentina',36),
('colombia','Colombian cinema',null,'Americas','Colombia',37),
('chile','Chilean cinema',null,'Americas','Chile',38),
('cuba','Cuban cinema',null,'Americas','Cuba',39),
('uk','British cinema',null,'Europe','United Kingdom',40),
('france','French cinema',null,'Europe','France',41),
('italy','Italian cinema',null,'Europe','Italy',42),
('germany','German cinema',null,'Europe','Germany',43),
('spain','Spanish cinema',null,'Europe','Spain',44),
('russia','Russian cinema',null,'Europe','Russia and the Soviet Union',45),
('denmark','Danish cinema',null,'Europe','Denmark',46),
('sweden','Swedish cinema',null,'Europe','Sweden',47),
('norway','Norwegian cinema',null,'Europe','Norway',48),
('finland','Finnish cinema',null,'Europe','Finland',49),
('iceland','Icelandic cinema',null,'Europe','Iceland',50),
('poland','Polish cinema',null,'Europe','Poland',51),
('czechia','Czech cinema',null,'Europe','Czech Republic and Czechoslovakia',52),
('ireland','Irish cinema',null,'Europe','Ireland',53),
('greece','Greek cinema',null,'Europe','Greece',54),
('romania','Romanian cinema',null,'Europe','Romania',55),
('nollywood','Nollywood',null,'Middle East & Africa','Nigeria',56),
('ghallywood','Ghallywood',null,'Middle East & Africa','Ghana',57),
('riverwood','Riverwood',null,'Middle East & Africa','Kenya',58),
('bongowood','Bongowood',null,'Middle East & Africa','Tanzania',59),
('southafrica','South African cinema',null,'Middle East & Africa','South Africa',60),
('egypt','Egyptian cinema',null,'Middle East & Africa','Egypt',61),
('turkey','Turkish cinema',null,'Middle East & Africa','Turkey (Yeşilçam)',62),
('iran','Iranian cinema',null,'Middle East & Africa','Iran',63),
('israel','Israeli cinema',null,'Middle East & Africa','Israel',64),
('morocco','Moroccan cinema',null,'Middle East & Africa','Morocco',65),
('australia','Australian cinema',null,'Oceania','Australia',66),
('newzealand','New Zealand cinema',null,'Oceania','New Zealand',67);
